### ISSUE TITLE
Publish version 1.1.2

### ISSUE THREAD

**Issue by fedragon** [massung/elm-css#4]
Hi @massung,

I see that, following my PR, you created a `1.2.0` tag but the latest version (compatible with Elm 0.19) is actually `1.1.2`, so your library is still considered "not updated" by `elm install`. Can you please create a new tag?

**Comment by massung** [comment]
Done. Let me know if that worked for you.

**Comment by massung** [comment]
Done. Let me know if this doesn't fix the issue for you (it's been a while since I've used Elm).

**Comment by fedragon** [comment]
@massung Did not fix it yet, unfortunately: I think you haven't run `elm publish` yet, to make it visible in the package repository. I just tried doing so on your behalf and got this:

```
  ● Found README.md
  ✗ Problem with your LICENSE

-- NO LICENSE FILE ----------------------------------------------------- LICENSE

By publishing a package you are inviting the Elm community to build upon your
work. But without knowing your license, we have no idea if that is legal!

Once you pick an OSI approved license from <https://spdx.org/licenses/>, you
must share that choice in two places. First, the license identifier must appear
in your elm.json file. Second, the full license text must appear in the root of
your project in a file named LICENSE. Add that file and you will be all set!
```

So yeah, can you please pick a license and run it again? :)

**Comment by massung** [comment]
@fedragon So, looks like there was a bit more work to publishing...

In 0.19 the `toString` method was removed (well, renamed to `Debug.toString`). This is fine for a few places, which turn into `String.fromInt`. But, the CSS generated before made heavy use of `toString` when it came to the `Id` and `Class` types. For example:

```elm
type Id = MyId
type Class = MyClass

rules = 
    [ { selectors=[Css.Id MyId], ... }
    , { selectors=[Css.Class MyClass], ... }
    ]
```

Converting `Css.Id MyId` to `#MyId` required the use of `toString MyId`, which no longer exists. Replacing it with `Debug.toString` fails to publish (correctly). And Elm doesn't have type classes, so it's not possible to do something like:

```elm
type alias stylesheet (Show id) (Show cls) msg = ...
```

Which would allow the end-user to implement their own version of `toString` for their selector IDs and classes. _Note: that would still annoy me as a programmer having to do that, though._

So, at this point I'm looking for suggestions.

If `id` and `cls` become just strings, then this module ceases being type safe and loses a sizable chunk of its value. 

The `stylesheet` function could take functions: `id -> String` and `cls -> String`, but that's probably quite annoying.

Perhaps there is something in 0.19 available that I'm missing?

**Comment by fedragon** [comment]
Hi @massung sorry for the late reply. I have been trying to find another solution in the past days but to no avail, so far... which is very disappointing because type safety is indeed a good chunk of this module's value.
